# Steps:
# 1. Fill web-production image.

version: "3.5"

services:
  api-production:
    image: gcr.io/geniem-production/client-opinvoimala-backend:production-latest

    container_name: api-production

    hostname: ${HOSTNAME_PREFIX}-api-production

    restart: "no"

    networks:
      - backend-production

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/devops/logs/production/api:/mnt/devops/logs/production/api

  db-production:
    image: gcr.io/geniem-devops/mariadb:10.5.9

    container_name: db-production

    hostname: ${HOSTNAME_PREFIX}-db-production

    restart: "no"

    volumes:
      - /mnt/devops/mysql/production:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

    networks:
      - backend-production

networks:
  backend-production:
    external:
      name: backend-production